name: 'Deploy to On-Premises Kubernetes cluster'
description: 'Deploys an application in an On-Premises Kubernetes cluster based in a GitOps repository'
author: MP-ES
branding:
  icon: 'command'
  color: 'purple'
inputs:
  k8s_envs:
    description: 'Multiline input where each line contains the name of a Kubernetes environment defined in the GitOps repository'
    required: true
  manifest_dir:
    description: 'Path to the manifest directory, with files to be used for deployment'
    required: false
    default: 'kubernetes'
  repo_token:
    description: 'Personal access token (PAT) used to manage comments on pull request'
    required: false
    default: ${{ github.token }}
  gitops_token:
    description: "GitHub PAT with read permission on GitOps repository, if it's private"
    required: false
  strategy:
    description: 'Deployment strategy to be used. Allowed values are none, canary and blue-green'
    required: false
    default: 'none'
outputs:
  status:
    description: 'JSON object with the status of deployment by K8S environment'
runs:
  using: docker
  # image: docker://mpespiritosanto/k8s-deploy:2.0.1
  image: Dockerfile
  args:
    - ${{ inputs.k8s_envs }}
    - ${{ inputs.manifest_dir }}
    - ${{ inputs.repo_token }}
    - ${{ inputs.gitops_token }}
    - ${{ inputs.strategy }}
