name: "Deploy to On-Premises Kubernetes cluster"
description: "Deploys an application in an On-Premises Kubernetes cluster based in a GitOps repository"
author: MP-ES
branding:
  icon: "command"
  color: "purple"
inputs:
  k8s-envs:
    description: "Multiline input where each line contains the name of a Kubernetes environment defined in the GitOps repository"
    required: true
  manifest-dir:
    description: "Path to the manifest directory, with files to be used for deployment"
    required: false
    default: "kubernetes"
  gitops-token:
    description: "GitHub PAT with read permission on GitOps repository, if it's private"
    required: false
  strategy:
    description: "Deployment strategy to be used. Allowed values are none, canary and blue-green"
    required: false
    default: "none"
outputs:
  status:
    description: "JSON object with the status of deployment by K8S environment"
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.k8s-envs }}
    - ${{ inputs.manifest-dir }}
    - ${{ inputs.gitops-token }}
    - ${{ inputs.strategy }}
