name: Pull request action test

on:
  pull_request:
    branches:
      - main

jobs:
  action_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Call the local action
        uses: ./
        id: action
        with:
          gitops-token: ${{ secrets.GITOPS_TOKEN }}
          k8s-envs: |
            dev
            app
          manifest-dir: kubernetes
      - name: Get the output
        run: echo "${{ steps.action.outputs.test }}"
