name: Release

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate docker image tag on action.yml file
        run: echo "current_action_docker_tag=$(echo refs/tags/v$(grep 'image' action.yml | cut -d':' -f4 | xargs))" >> $GITHUB_ENV

      - if: ${{ env.current_action_docker_tag != github.ref  }}
        run: echo "::error ::Current action docker image tag '${{ env.current_action_docker_tag }}' is different from expected '${{ github.ref }}' value";exit 1

  release:
    runs-on: ubuntu-latest

    needs:
      - validate

    if: ${{ success() }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: mpespiritosanto/k8s-deploy
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern=v{{major}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: slim.dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
